displayName: Auth With Exceptions
type: middleware
import: github.com/brinkmann-mi/traefik-auth-with-exceptions

summary: |
  Traefik plugin for Basic Access Authentication with exceptions.
  (e.g. exclude IPs or hosts)

testData:
  authExtraTime: 300ms
  basicAuth:
    users:
      - user:{SHA}Et6pb+wgWTVmq3VpLJlJWWgzrck=  # user:user
  exceptions:
    ipList:
      - 192.168.1.1
      - 192.168.2.0/24
    hostList:
      - example.com
    hostUpdateInterval: 30m
